[build]
  command = "bundle exec jekyll build --incremental"
  functions = "netlify/functions"
  publish = "_site"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true